services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build: .
    container_name: nestjs_app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: 'postgresql://your_user:your_password@postgres:5432/your_database'
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
