services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: health_core
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build: .
    container_name: nestjs_app
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
